CREATE TABLE TRAIN(TRAIN_NO int NOT NULL, SOURCE_TRAIN varchar(255), Availability varchar(255), Train_Name varchar(255),Train_Type varchar(255),Destination varchar(255),PRIMARY KEY (TRAIN_NO));

CREATE TABLE USER_TABLE(USER_ID int NOT NULL,USER_TYPE varchar(255) ,F_NAME varchar(255),L_NAME varchar(255) ,AGE int,DOB DATE,PHONE varchar(255),STREET_NO varchar(255),PIN_CODE varchar(255),PRIMARY KEY(USER_ID));

CREATE TABLE PAYMENT_INFO (TRANSACTION_NO int NOT NULL,PRICE int,BANK varchar(255),CARD_NO int,PRIMARY KEY(TRANSACTION_NO));

CREATE TABLE FARE_TABLE(TRAIN_TYPE varchar(255) NOT NULL,COMPARTMENT_NO int,FARE_PER_KM int,PRIMARY KEY(TRAIN_TYPE));

CREATE TABLE COMPARTMENT(TRAIN_NO int ,TYPE varchar(255) ,AVAILABILITY varchar(255),COMPARTMENT_NO int,CAPACITY int ,FOREIGN KEY (TRAIN_NO) REFERENCES TRAIN (TRAIN_NO));

CREATE TABLE ROUTE_INFO(TRAIN_NO int ,TYPE varchar(255) ,FROM_STATION_NO int,FROM_STATION_NAME varchar(255),TO_STATION_NO int,TO_STATION_NAME varchar(255),DISTANCE double,FOREIGN KEY (TRAIN_NO) REFERENCES TRAIN (TRAIN_NO));

CREATE TABLE TICKET (PNR int NOT NULL, COMPARTMENT_TYPE varchar(255),COMPARTMENT_NO varchar(255),ARRIVAL_TIME time,DEPARTURE_TIME time ,TRAIN_NO int ,ARRIVAL varchar(255),DEPARTURE varchar(255),TRAVEL_DATE date,NAME varchar(255),AGE int ,SEAT_NO int ,USER_ID int ,TRAIN_TYPE varchar(255),PRIMARY KEY(PNR),FOREIGN KEY (TRAIN_NO) REFERENCES TRAIN (TRAIN_NO),FOREIGN KEY (USER_ID) REFERENCES USER_TABLE(USER_ID),FOREIGN KEY (TRAIN_TYPE) REFERENCES FARE_TABLE (TRAIN_TYPE));


CREATE TABLE HAS(PNR int NOT NULL,TRANSACTION_NO int NOT NULL,PRIMARY KEY (PNR, TRANSACTION_NO),FOREIGN KEY (PNR) REFERENCES TICKET (PNR),FOREIGN KEY (TRANSACTION_NO ) REFERENCES PAYMENT_INFO (TRANSACTION_NO ));

CREATE TABLE CHECKS(TRAIN_NO int NOT NULL,USER_ID int NOT NULL,PRIMARY KEY (TRAIN_NO, USER_ID),FOREIGN KEY (TRAIN_NO) REFERENCES TRAIN (TRAIN_NO),FOREIGN KEY (USER_ID) REFERENCES USER_TABLE (USER_ID));


#2)
ALTER TABLE TRAIN MODIFY TRAIN_NAME varchar(255) NOT NULL, MODIFY TRAIN_TYPE varchar(255) NOT NULL;

#3)
ALTER TABLE  COMPARTMENT ALTER AVAILABILITY SET DEFAULT 'Yes';

#4)
ALTER TABLE TRAIN ADD unique(TRAIN_NAME);

#5)
ALTER TABLE TICKET ADD CHECK(AGE > 5);

#6)
 RENAME TABLE USER_TABLE TO USER_INFO;

#7)
CREATE VIEW VIEW_INFO AS SELECT TRAIN_NO,ROUTE_INFO,Availability FROM TRAIN;

#8)
TRUNCATE TABLE TICKET;
DROP TABLE TICKET;