CREATE DATABASE PES1UG20CS462;
USE PES1UG20CS462;


CREATE TABLE TRAIN(
Train_no INT PRIMARY KEY NOT NULL, 
Name VARCHAR(50),
Arrival TIME,
Destination VARCHAR(30),
Availability VARCHAR(20),
Train_Type VARCHAR(20)
);


CREATE TABLE COMPARTMENT( 
Type VARCHAR(20),
Compartment_no INT PRIMARY KEY,
Capacity INT,
Availability VARCHAR(20),
Train_no INT,
FOREIGN KEY (Train_no)
REFERENCES TRAIN(Train_no)
);


CREATE TABLE ROUTE_INFO(
From_Station_No INT,
From_Station_Name VARCHAR(30),
To_Station_No INT,
To_Station_Name VARCHAR(30),
Distance INT,
Train_no INT,
PRIMARY KEY(From_Station_No, To_Station_No),
FOREIGN KEY (Train_no)
REFERENCES TRAIN(Train_no)
);


CREATE TABLE USER(
User_ID VARCHAR(20) PRIMARY KEY,
User_Type VARCHAR(20),
FName VARCHAR(50),
LName VARCHAR(50),
Age INT,
DOB DATE,
Pincode INT,
Street_No VARCHAR(20)
);


CREATE TABLE USER_TRAIN(
Train_no INT,
User_ID VARCHAR(20),
Date_Timestamp DATETIME,
PRIMARY KEY(Train_No, User_ID, Date_Timestamp),
FOREIGN KEY(Train_no)
REFERENCES TRAIN(Train_no),
FOREIGN KEY(User_ID)
REFERENCES USER(User_ID)
);


CREATE TABLE USER_PHONE(
User_ID VARCHAR(20),
Phone_No INT,
PRIMARY KEY(User_ID, Phone_No),
FOREIGN KEY(User_ID)
REFERENCES USER(User_ID)
);


CREATE TABLE TICKET(
PNR VARCHAR(10),
Train_no INT,
Travel_Date DATE,
Departure VARCHAR(20),
Arrival VARCHAR(20),
Departure_Time TIME,
Arrival_Time TIME,
User_ID VARCHAR(20),
Train_Type VARCHAR(20),
Compartment_Type VARCHAR(20),
Compartment_no INT,
PRIMARY KEY (PNR),
FOREIGN KEY(User_ID)
REFERENCES USER(User_ID)
);


CREATE TABLE PAYMENT_INFO(
Transaction_ID VARCHAR(10) PRIMARY KEY,
Bank VARCHAR(20),
Card_Number VARCHAR(20),
Price INT,
PNR VARCHAR(20),
FOREIGN KEY (PNR)
REFERENCES TICKET(PNR)
);


CREATE TABLE TICKET_PASSENGER(
Seat_No VARCHAR(20) PRIMARY KEY,
Name VARCHAR(50),
Age INT,
PNR VARCHAR(10),
FOREIGN KEY (PNR)
REFERENCES TICKET(PNR)
);


CREATE TABLE FARE_TABLE(
Train_Type VARCHAR(20),
Compartment_Type VARCHAR(20),
Fare_Per_KM INT,
PRIMARY KEY(Train_Type, Compartment_Type)
);


ALTER TABLE TRAIN MODIFY Name VARCHAR(50) NOT NULL, MODIFY Train_Type VARCHAR(20) NOT NULL;


ALTER TABLE COMPARTMENT ALTER Availability SET DEFAULT 'Yes';


ALTER TABLE TRAIN ADD unique(Name);


ALTER TABLE TICKET_PASSENGER ADD CHECK(Age > 5);


RENAME TABLE TICKET TO TICKET_INFO;


TRUNCATE TABLE FARE_TABLE;
DROP TABLE TICKET;